
24-06-2020 21-46-06: Starting game vs Bot_Stardust_II
C:\Users\CATIC\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\client.py:309: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x000002647EC68C88>
  **kwargs)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
D:\Starcraft II\Ladder\Bots\Bot_IV\__init__.py:87: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
